WIP: exceptions during command calls / handling
EVerest/everest-framework pull request #210
Opened 2024-10-14 14:00 UTC by hikinggrass

2025-01-24 18:04 UTC, hikinggrass commented on include/framework/everest.hpp
> +enum class ErrorType {
`ErrorType` might be a bit vague and could lead to confusions with the "error framework"

2025-02-28 12:00 UTC, hikinggrass commented on include/framework/everest.hpp
> +    Unknown
remove Unknown

2025-02-28 12:00 UTC, hikinggrass commented on include/framework/everest.hpp
> +enum class ErrorType {
Maybe call this `CallCmdEvent` or `CmdEvent`

2025-02-28 12:00 UTC, hikinggrass commented on include/framework/everest.hpp
> +    ErrorType type;
event

2025-02-28 12:00 UTC, hikinggrass commented on include/framework/everest.hpp
> +struct ErrorMessage {
`CmdResultError`

2025-02-28 12:00 UTC, hikinggrass commented on include/framework/everest.hpp
> +
Maybe already define exceptions for the other `CallCmdEvent`s

2025-02-28 12:00 UTC, hikinggrass commented on lib/everest.cpp
> +            error = ErrorMessage{ErrorType::HandlerException, e.what()};
re-throw after result has been sent to caller so the handler still crashes

2025-02-28 12:00 UTC, hikinggrass commented
TODO: add test-cases

2025-03-31 16:55 UTC, hikinggrass commented on lib/everest.cpp
> +        }
TODO: should this be configurable? default = rethrow (which is very similar to the current behavior) but can be turned off?

2025-04-03 08:29 UTC, dorezyuk commented on include/utils/types.hpp
> +    Shutdown
should we add also a notyetready?

2025-04-04 17:42 UTC, Pietfried commented on lib/conversions.cpp
> +        break;
Can be removed here and following
```suggestion
```

2025-04-04 17:42 UTC, Pietfried commented on lib/everest.cpp
> +    }
nit: reads a little better
```suggestion
if (result.error.has_value()) {
        const auto& error = result.error.value();
        const std::string err_msg = fmt::format("{}", error.msg);
    
        switch (error.event) {
            case CmdEvent::HandlerException:
                throw HandlerException(err_msg);
            case CmdEvent::Timeout:
                throw CmdTimeout(err_msg);
            default:
                throw CmdError(fmt::format("{}: {}", conversions::cmd_event_to_string(error.event), error.msg));
        }
    }
    
    if (!result.result.has_value()) {
        throw CmdError("Command did not return result");
    }
    
    return result.result.value();
```

2025-04-04 17:42 UTC, Pietfried commented on lib/everest.cpp
> +            error = CmdResultError{CmdEvent::HandlerException, "Unknown exception"};
couldnt we use `std::current_exception()` here as well?

2025-04-04 17:42 UTC, Pietfried commented on lib/everest.cpp
> +        }
For now I would just rethrow it and possibly make it configurable in a subsequent PR after we have discussed and analyzed potential implications of that

2025-04-07 07:01 UTC, dorezyuk commented on include/utils/types.hpp
> +    std::optional<CmdResultError> error;
to my understanding they are mutually exclusive - can we express that through the type system, e.x a variant?

2025-04-07 12:28 UTC, hikinggrass commented on include/utils/types.hpp
> +    Shutdown
added NotReady enum

2025-04-07 12:32 UTC, hikinggrass commented on include/utils/types.hpp
> +    std::optional<CmdResultError> error;
A variant here might a bit tricky at the moment due to `CmdResultError` being convertible to `json` and result being a `json` type. But let's keep this in mind during the upcoming refactorings in this part of the code

2025-04-07 12:33 UTC, hikinggrass commented on lib/everest.cpp
> +            error = CmdResultError{CmdEvent::HandlerException, "Unknown exception"};
added usage of `std::current_exception()`

2025-04-08 11:01 UTC, hikinggrass commented on lib/everest.cpp
> +        default:
TODO: use other defined exceptions here

2025-04-08 11:26 UTC, hikinggrass commented on include/utils/types.hpp
> +class CmdError : public std::runtime_error {
move this into a separate file

2025-07-04 11:07 UTC, hikinggrass commented on lib/everest.cpp
> +        }
default is now still the current behavior, but the new behavior can be turned on by setting the following in a config:
```yaml
settings:
  forward_exceptions: true
````

2025-07-08 20:05 UTC, Pietfried requested changes
lgtm, except one comment in line

2025-07-08 20:05 UTC, Pietfried commented on lib/everest.cpp
> +        default:
This doesnt look like it is resolved?

What about?
MessageParsingFailed
SchemaValidationFailed
Shutdown
NotReady

2025-07-08 21:56 UTC, hikinggrass commented on lib/everest.cpp
> +        default:
Good catch, I have added the missing exception throws

2025-07-09 07:08 UTC, Pietfried approved these changes

2025-07-09 14:01 UTC, merged