Use shared error map
EVerest/everest-framework pull request #214
Opened 2024-10-28 06:18 UTC by dorezyuk

Currently the error map is copy constructed and then placed into a shared pointer which results in the error map not being really shared between the different classes. This Pr fixes it.

2024-10-28 06:20 UTC, dorezyuk commented on include/utils/error/error_factory.hpp
> -    const std::shared_ptr<ErrorTypeMap> error_type_map;
I suppose the intention was to say a shared pointer to a const ErrorMap and not a const shared pointer to a (mutable) ErrorMap

2024-10-28 06:21 UTC, dorezyuk commented on include/utils/error/error_manager_req.hpp
> -struct ErrorTypeMap;
I don't really get what the idea behind all the forward defines was - I've removed it to just use the ErrorTypeMapPtr type

2025-01-17 01:39 UTC, andistorm requested changes
Thanks for your work here @dorezyuk,

I really would like to merge the optimization of sharing the pointer instead of copying the ErrorTypeMap.
Could you please move the style changes in another PR/Discussion?
Regarding the forward declarations I see a disadvantage in removing them since they can safe compile time by reducing dependencies between the header files.

Please let me know if you have further questions to my comments

2025-01-17 01:39 UTC, andistorm commented on include/utils/error/error_type_map.hpp
> +
I would prefer to keep using `std::shared_ptr<const ErrorTypeMap>` since it fits the style arround here

2025-01-17 01:39 UTC, andistorm commented on include/utils/error/error_type_map.hpp
> +#include <memory>
```suggestion
```
This dependency can be avoided, when not defining this `ConstPtr`

2025-01-17 01:39 UTC, andistorm commented on include/utils/error/error_factory.hpp
> -struct ErrorTypeMap;
I would like to keep this forward declaration to avoid unnecessary dependencies in all these header files

2025-01-17 01:39 UTC, andistorm commented on include/utils/error/error_manager_req.hpp
> -struct ErrorTypeMap;
The idea of forward declarations is to avoid including dependencies in the header file to reduce compile times after changing something in the included files

2025-01-17 01:39 UTC, andistorm commented on lib/config.cpp
> +Config::Config(std::shared_ptr<RuntimeSettings> rs, bool manager) : rs(rs), manager(manager), error_map{nullptr} {
This default value is not needed, especially because it is initialized in the body of the constructor

2025-01-17 01:39 UTC, andistorm commented on lib/everest.cpp
> +                                                      publish_raised_error, publish_cleared_error);
I don't really get what changed here

2025-01-17 07:18 UTC, dorezyuk commented on include/utils/error/error_type_map.hpp
> +
not sure if i understand - we're using it

2025-01-17 07:19 UTC, dorezyuk commented on include/utils/error/error_type_map.hpp
> +#include <memory>
also not sure if I understand - we use it in this library a lot. What do you mean with "avoid" the dependency? Are you concerned about the preprocessor adding this?

2025-12-01 18:59 UTC, andistorm commented
I’m closing this PR due to prolonged inactivity, unresolved comments, and the fact that the changes are somewhat outdated. Another important reason is the upcoming restructuring of the code, as this repository will be integrated into the monorepo. Given these factors, it doesn’t make sense to move this PR forward at this time.

@dorezyuk , thank you for the contribution and discussion so far.

2025-12-01 18:59 UTC, closed without merging